# Generated by Django 4.2.23 on 2025-06-28 05:24

from django.db import migrations, models
import django.utils.timezone
from datetime import datetime, time


def set_timestamps(apps, schema_editor):
    WeatherData = apps.get_model("main", "WeatherData")
    for record in WeatherData.objects.all():
        # Set timestamp to noon on the date
        record.timestamp = datetime.combine(record.date, time(12, 0))
        record.save()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_dataset_id_alter_dataset1_id_alter_dataset2_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weatherdata",
            options={"ordering": ["-timestamp"]},
        ),
        # First add the timestamp field as nullable
        migrations.AddField(
            model_name="weatherdata",
            name="timestamp",
            field=models.DateTimeField(null=True),
        ),
        # Then run the data migration
        migrations.RunPython(set_timestamps),
        # Then make the field non-nullable with a default
        migrations.AlterField(
            model_name="weatherdata",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name="weatherdata",
            unique_together={("timestamp", "location")},
        ),
        migrations.AddIndex(
            model_name="weatherdata",
            index=models.Index(
                fields=["timestamp"], name="main_weathe_timesta_119551_idx"
            ),
        ),
    ]
