# Generated by Django 4.2.23 on 2025-06-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_weatherdata_options_weatherdata_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together={('date', 'timestamp', 'location')},
        ),
    ]
